document.write("<h1>Elzero</h1>");
document.querySelector("h1").style.color = 'blue';
document.querySelector("h1").style.fontSize = '80px';
document.querySelector("h1").style.fontWeight = 'bold';
document.querySelector("h1").style.textAlign = 'center';
document.querySelector("h1").style.fontFamily = 'arial';
console.log("%cELZERO %cWEB %cSCHOOL", "color: red; font-size: 30px","color: green; font-size: 30px; font-weight:bold;","background-color: blue; color:white; font-size: 30px;") ;
console.group("Group 1");
console.log("Message One");
console.log("Message Two");
console.group("Child Group");
console.log("Message One");
console.log("Message Two");
console.group("Grand Child Group");
console.log("Message One");
console.log("Message Two");
console.groupEnd();
console.groupEnd();
console.groupEnd();
console.group("Group 2");
console.log("Message One");
console.log("Message Two");
console.groupEnd();
console.table(["Elezero","Ahmed","Sameh","Gamal","Aya"]);